sudo: false
language: scala
jdk:
  # - openjdk7
  - oraclejdk7
  - oraclejdk8
scala:
  - 2.12.4

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start
